Add fio-parse-jsons.py to parse a set of json FIO files. Extend librb…
ceph/cbt pull request #306
Opened 2024-05-02 13:05 UTC by perezjosibm

…dfio for a new workloads block.

This is my first PR, please be gentle in the review.

-  Extend the test plan .yml with a new block section 'workloads' to allow a list of performance tests to be indicated, each with its own range of iodepth and numjobs to iterate. An example of this is provided in `example/rbd_fio_test.yml`

- Extend librbdfio.py with support for such 'workloads' block.

- Add a new `tools/fio-parse-jsons.py` script to parse a set of .JSON FIO output files (extending the existing script with similar name in singular).

Cheers,

2024-05-15 09:11 UTC, perezjosibm commented
@markhpc : here is my PR for the CBT extensions, would you be able to review please? thanks!

2024-05-22 14:31 UTC, sseshasa commented
@perezjosibm I have started taking a look at this. Please allow me some time to understand the changes. I plan to complete the review by the end of this week or in the worst case early next week due to the long weekend here.

2024-05-30 08:23 UTC, sseshasa requested changes
I have added my first set of review comments. Will continue the review.

2024-05-30 08:27 UTC, sseshasa commented
> I have added my first set of review comments. Will continue the review.

Hmm...looks like my initial comments were lost. I will add them again. Sorry about that.

2024-05-30 08:55 UTC, sseshasa requested changes
Okay, now my first set of comments are added. Will continue reviewing this.

2024-05-30 08:55 UTC, sseshasa commented on benchmark/benchmark.py
> +        logger.info("Results dir: %s", self.archive_dir ),
Is this log necessary since the archive location is known to the user?

2024-05-30 08:55 UTC, sseshasa commented on benchmark/librbdfio.py
> +        self.ioengine = config.get('ioengine', 'libaio')
For librbdfio, the ioengine is hardcoded to 'rbd' in the fio_cmd. The uncommenting of this line has no effect and can therefore be reverted.

2024-05-30 08:55 UTC, sseshasa commented on benchmark/librbdfio.py
> +        self.set_global_fio_options()
I think this call can be moved to `initialize()` and can be called if `self.workloads` is defined. See my suggestion in the comment for the `initialize()` function.

You can also consider renaming this function to `backup_global_fio_options()`

2024-05-30 08:55 UTC, sseshasa commented on benchmark/librbdfio.py
> +        self.vol_name = config.get('vol_name', 'cbt-librbdfio-`%s`-%d' )
`self.vol_name` is unused and therefore can be removed.

2024-05-30 08:55 UTC, sseshasa commented on benchmark/librbdfio.py
> +    def get_workloads(self):
This function only logs the workload details. This can be moved to `initialize()`.

2024-05-30 08:55 UTC, sseshasa commented on benchmark/librbdfio.py
> +    def get_precondition(self):
This function only logs the precondition details. This can be moved to `initialize()`.

2024-05-30 08:55 UTC, sseshasa commented on benchmark/librbdfio.py
> +        if not self.skip_monitoring:
The actual sleep time is different from what is logged. I'd suggest using a new config variable called `idle_monitor_sleep` and use that here. This removes the need for `self.skip_monitoring` boolean.

2024-05-30 08:55 UTC, sseshasa commented on benchmark/librbdfio.py
> +        self.get_precondition()
Following on from one of my previous comments, I'd suggest the following:

```suggestion
    def initialize(self):
       ...
       if (self.workloads):
         self.set_global_fio_options()
         logger.info(" %d Workloads:\n....)
         logger.info("Precond:\n ...)
      ...
```

2024-05-30 08:55 UTC, sseshasa commented on benchmark/librbdfio.py
> +            enable_monitor=True
nit: space before and after '='.

2024-05-30 08:55 UTC, sseshasa commented on benchmark/librbdfio.py
> +                enable_monitor=bool(test['monitor'])
nit: Space before and after  '='.

2024-05-30 08:55 UTC, sseshasa commented on benchmark/librbdfio.py
> +                        time.sleep(30); # ramp up time before measuring
Use the `self.ramp' here for sleep.

2024-05-30 08:55 UTC, sseshasa commented on benchmark/librbdfio.py
> +
nit: Extraneous new line. Maintain single line gap between function definitions.

2024-05-30 08:55 UTC, sseshasa commented on benchmark/librbdfio.py
> +
nit: Extraneous new line.

2024-05-30 08:55 UTC, sseshasa commented on benchmark/librbdfio.py
> +
nit: Extraneous new line. Noticed that a new line is introduced before all functions. Please revert it in all places.

2024-05-30 13:22 UTC, sseshasa requested changes
I am done with the first pass and have provided my comments. 

- I mainly focused on the main parts of the code changes related to benchmark. 
- One important recommendation is to ensure through testing that the original behavior of librbdfio benchmark is preserved

2024-06-04 08:48 UTC, perezjosibm commented on benchmark/benchmark.py
> +        logger.info("Results dir: %s", self.archive_dir ),
Being a user for the first time to CBT I was not aware of the location, I can replace it with a debug log sentence instead.

2024-06-04 08:49 UTC, perezjosibm commented on benchmark/librbdfio.py
> +        self.ioengine = config.get('ioengine', 'libaio')
Ok, I will remove it

2024-06-04 08:50 UTC, perezjosibm commented on benchmark/librbdfio.py
> +        self.set_global_fio_options()
Ok, makes sense

2024-06-04 08:50 UTC, perezjosibm commented on benchmark/librbdfio.py
> +        self.vol_name = config.get('vol_name', 'cbt-librbdfio-`%s`-%d' )
Ah yes, I was experimenting and forgot to remove it, thanks!

2024-06-04 09:06 UTC, perezjosibm commented on benchmark/librbdfio.py
> +    def get_workloads(self):
Yeah, I was wondering whether these methods -- get_workloads() -- might need to grow, but probably wont, so I'll remove them. The logging was only to verify that it was being created correctly, so might no longer needed. Or simply as in a debug log.

2024-06-04 09:07 UTC, perezjosibm commented on benchmark/librbdfio.py
> +                enable_monitor=bool(test['monitor'])
Yeah, I thought I had run the lint, will double check 👍

2024-06-04 09:07 UTC, perezjosibm commented on benchmark/librbdfio.py
> +
Will do

2024-06-04 09:15 UTC, perezjosibm commented on cbt.py
> +                if not b.exists() and not settings.cluster.get('is_teuthology', False):
The change was to fix a bug that was occurring on fresh new runs, but I'm happy to reverted. Will run further tests to confirm  👍

2024-06-04 10:06 UTC, perezjosibm commented on settings.py
> +    #logger.debug("Nodes : %s", str_nodes)
Yes, it floods the log since its called several times by several methods

2024-06-04 10:08 UTC, perezjosibm commented on monitoring.py
> +        else:
Yes, the 'else' path in this case is for remote nodes 😃

2024-06-04 10:09 UTC, perezjosibm commented on tools/fio-parse-jsons.py
> +#!/usr/bin/python3
Makes sense, yes I'll do that asap

2024-06-04 10:15 UTC, perezjosibm commented on common.py
> +    if len(nodes_list) < 1:
Its a bug fix since the logic was returning None when there were actual nodes in the list 😄

2024-06-04 12:42 UTC, perezjosibm commented on tools/fio-parse-jsons.py
> +#!/usr/bin/python3
Hi @sseshasa: I've opened PR https://github.com/ceph/cbt/pull/307 for only the new script, thanks!

2024-06-04 15:28 UTC, perezjosibm commented on benchmark/librbdfio.py
> +        if not self.skip_monitoring:
I think the flag skip_monitoring is still useful for test where we don't want/need to monitor, for example when pre-filling the volumes, etc.

2024-06-04 16:49 UTC, perezjosibm commented on benchmark/librbdfio.py
> +        self.get_precondition()
I've refactored in an equivalent way, only the precondition has now been removed since was not used, probably a feature for a next PR

2024-06-04 17:31 UTC, perezjosibm commented on cbt.py
> +                logger.info("Running benchmark %s == iteration %d =="%(b,iteration))
I've changed to use f-strings instead 👍

2024-06-05 10:02 UTC, sseshasa commented on tools/fio-parse-jsons.py
> +#!/usr/bin/python3
Hi @perezjosibm I mean introduce the new script in a new commit as a part of this PR(#306) itself.

2024-06-05 15:15 UTC, perezjosibm commented on tools/fio-parse-jsons.py
> +#!/usr/bin/python3
Hi @sseshasa sorry about that, I hope you don't mind reviewing them separately. I have updated this PR with the requested changes to the best of my understanding. I did a `git ci -s -a --amend` to have them all in a single batch. Many thanks.

2024-06-05 15:19 UTC, perezjosibm commented
Tested the remote path by running CBT from my laptop, connecting to the remote nodes:
![Screenshot 2024-06-05 at 12 51 09](https://github.com/ceph/cbt/assets/23522684/ccfb08ac-1c97-40f6-86e9-fedab5df1255)

2024-06-05 19:15 UTC, perezjosibm commented
Apologies, I just fixed some subtle bugs I introduced when doing the changes that didn't show up in the preliminary tests, I need to push the fixes again, sorry for the disturbance!

2024-06-06 09:27 UTC, perezjosibm commented
Hi @sseshasa changes are ready for review please, many thanks!

2024-06-09 13:24 UTC, sseshasa approved these changes
Just added a couple of new review comments. But this looks good to me.  I would prefer another pair of eyes to have a look at this as well. @markhpc can you please review this?

2024-06-09 13:24 UTC, sseshasa commented on cluster/cluster.py
> +        #self.idle_monitor_sleep = config.get('idle_monitor_sleep',60)
Can this commented line be removed?

2024-06-10 08:59 UTC, perezjosibm commented on benchmark/librbdfio.py
> +    linrbdfio.py -- module to support the FIO benchmark exercising RBD.
Good spot, thank you

2024-07-22 16:20 UTC, perezjosibm commented on cluster/cluster.py
> +        #self.idle_monitor_sleep = config.get('idle_monitor_sleep',60)
Done, I've updated with the minor fixes 👍

2024-07-22 16:22 UTC, perezjosibm commented
Hi @Matan-B wonder if you could please review/approve this PR?, Thanks

2024-07-23 15:39 UTC, merged